### ISSUE TITLE
Invalid cmap format

### ISSUE THREAD

**Issue by paulobrien** [MitchTalmadge/Emoji-Tools#21]
The tool returns 'invalid cmap table format' with the new improved Android emojis. :)

Example file attached. Thanks for a fantastic tool!

[NotoColorEmoji.ttf.zip](https://github.com/MitchTalmadge/Emoji-Tools/files/55369/NotoColorEmoji.ttf.zip)

**Comment by MitchTalmadge** [comment]
Thanks! I should have this issue solved soon.

**Comment by paulobrien** [comment]
Great, I look forward to it.

**Comment by MitchTalmadge** [comment]
I am now able to get the emojis to extract, and in the process of making that work, I figured out how to re-package the diversity and flag emojis , which was previously not possible with Emoji Tools. I am currently working on implementing it, and it may take a few days. I'll let you know when it works :) 
Thanks for your patience and support!

**Comment by MitchTalmadge** [comment]
The emojis now successfully extract and re-package after modification. I am working on a few more things, then I will update the guide and release 1.8. :)

**Comment by ayrton2510** [comment]
I'm also looking forward to the new version. Thanks for working on this tool.

**Comment by ayrton2510** [comment]
A question, can you check if chrome shows the emoji with a modified ttf file from 1.8? I'm using a modified ttf from a thread in XDA, but no emojis on chrome.

**Comment by dekefake** [comment]
I'm also looking forward for this tool lol. Waiting to make a new iOS emojis font for Android. Awesome work mate

**Comment by MitchTalmadge** [comment]
@ayrton2510 I'm not sure I understand your question, do you mean that you cannot access the emojis, or that they simply don't show up at all in the emojis section of the keyboard, or something else? Where are you trying to type in emojis?

**Comment by ayrton2510** [comment]
MitchTalmadge I'm running 6.0.1 on my nexus. Using the new keyboard and this ttf file (http://forum.xda-developers.com/android/software-hacking/mod-apple-8-3-diverse-color-emoji-t3136169/post61370793#post61370793). I can see the emojis on every app except for google chrome. I want to know if shows the emojis generated by your new tool.

**Comment by MitchTalmadge** [comment]
Another update: Unfortunately I might not be able to get OS X/iOS packaging abilities into 1.8 like I hoped to. There's a bug in fonttools, which I use for packaging, that is preventing it from working. As soon as the developers of fonttools fix the bug, I'll add in the support for OS X and iOS. Thanks for your understanding. (This does not prevent you from extracting OS X/iOS emojis and packaging them into an Android emoji font)

@ayrton2510 I'll have to try this out later and let you know. :)

**Comment by ayrton2510** [comment]
@MitchTalmadge Thanks.

**Comment by MitchTalmadge** [comment]
1.8 has been released! Thanks for everyone's patience. Get it in the releases section. Enjoy!

@ayrton2510 Emojis packaged by Emoji Tools 1.8 seem to appear just fine for me in Google Chrome. Try it out and let me know if you can't get it working :)
