### ISSUE TITLE
Error Code 6 when building

### ISSUE THREAD

**Issue by MrYawnie** [MitchTalmadge/Emoji-Tools#25]
Hey again,

I successfully added few completely new emojis manually to ttx, and was able to build the font file. I then tried to add 77 new emojis, and although going through the same procedures manually as before, I faced error code 6 when building. It states that i have incorrectly modified the .ttx file. Now I know i may have misspelled something, or something else happened, but i just don't know what, as the program doesn't tell me anything more. See the screenshot attached. 
So could it be possible to figure out which part of the ttx code triggered the error, as I added tens of thousands of lines code, so it's hard to find the mistake or whatever it is as you probably understand :)

![emojitoolserror](https://cloud.githubusercontent.com/assets/14262612/13367219/8823358a-dce9-11e5-9c26-b0eddfa696db.PNG)

**Comment by MitchTalmadge** [comment]
That error is caused when you have a glyph name specified in the ttx file but the associated .PNG file for it is missing. If you notice, all the PNG files are named by their Unicode glyph names. Is it possible you added the emojis into the ttx file but forgot to add PNG files for them in the emojis directory? I know it's a dumb requirement given that the data is already in the ttx file, but I didn't design the packager with modding friendliness in mind. That's something I'm trying to add in for the next version, but school and being sick and all that is getting in the way.

**Comment by MrYawnie** [comment]
I have added all .png's, and i just double checked it, and added all of them again. So unfortunately that's not the case. I will go through the glyph names and look for typing errors after work today. Hopefully i'll find one and that is the issue. If not, then i'm quite clueless.

**Comment by MrYawnie** [comment]
After trying several times and failing, i took a look into the logs in order to find a common error on each. And i did. It always failed after the same emoji, so i took a deeper look into the code and found one letter missing. Just a small typo. After fixing that, i was able to build the font file! Thanks a ton :)
