### ISSUE TITLE
Is it possible to name all emoji images with raw unicode code?

### ISSUE THREAD

**Issue by chika-kasymov** [MitchTalmadge/Emoji-Tools#35]
I've got an iOS project which should render emojis collection. I decided to add emoji images and map them with emojis in the database because when using raw text/string emojis there is a memory leak issue from Apple (iOS) side.

The easiest way to map is to use Unicode name for images, but some of the generated images with your tool contains letters and numbers to indicate gender, skin color and etc.

The question is can I change some of your code to generate image names without additional letters and numbers? As I understand I need to change **AppleExtractionWorker.java** file.

Thanks for any help!

**Comment by chika-kasymov** [comment]
Finally, I just write a small function to convert emoji raw Unicode value similar to generated image names.

**Comment by Denny2410** [comment]
Have you been able to package a font for iOS? I described my problem here: https://github.com/MitchTalmadge/Emoji-Tools/issues/36

**Comment by chika-kasymov** [comment]
@Denny2410 I didn't package a font. I added generated images to the project bundle and accessed them by plain `[UIImage imageWithContentsOfFile:]`.
